export const shoesData = [
  {
    id: 1,
    name: "Casual Sports Shoes Mens Cushioned ",
    brand: "Sports",
    price: 95,
    category: "Sneakers",
    description:
      "Men'S Cushioned Casual Sports Shoes - Featuring Breathable Mesh And PU Upper, Designed with Geometric Patterns, Lace-Up Style, And a Black And White Color Scheme, Providing a Comfortable Fit Suitable for Outdoor Running, Walking",
    imageURL: "/assests/men-sneakers-1/men-shoe-1.avif",
    images: [
      "/assests/men-sneakers-1/men-shoe-1.avif",
      "/assests/men-sneakers-1/men-shoe-2.avif",
      "/assests/men-sneakers-1/men-shoe-3.avif",
      "/assests/men-sneakers-1/men-shoe-4.avif",
    ],
    stock: 40,
    rating: "4.7",
    is_in_inventory: true,
    items_left: 40,
    slug: "Casual-Sports-Shoes",
    gender: "Mens",
  },

  {
    id: 2,
    name: "Fashion Mens Casual Shoes",
    brand: "Fashion",
    price: 120,
    category: "Sneakers",
    description: "Sneakers, All-Season Versatile Men's Plus Size Casual Shoes, Sporty Style Walking Shoes, Low-Top Black Casual Shoes, Men's High-Top Trendy Versatile Hiking Shoes for Running and Sports.",
    imageURL:"/assests/men-sneakers-2/men-shoe-1.avif",
    
    images: [
     "/assests/men-sneakers-2/men-shoe-1.avif",   
     "/assests/men-sneakers-2/men-shoe-2.avif",
     "/assests/men-sneakers-2/men-shoe-3.avif",
     "/assests/men-sneakers-2/men-shoe-4.avif",
    ],
    stock: 50,
    rating: "4.5",
    is_in_inventory: true,
    items_left: 30,
    slug: "Men's-Fashion-Casual-Sneakers",
    gender: "Mens",
  },

  {
    id: 3,
    name: "Breathable Mid-Top Sneakers",
    brand: "MAINALUN",
    price: 85,
    category: "Sneakers",
    description: "Breathable Mid-Top Sneakers, Heart & Music Graphic Design, Casual Streetwear Shoes for Couples, Valentine's Day & Birthday Gifts (Large Sizes Available), Cute Shoes, Comfort Footwear, Round Toe Design.",
    imageURL:"/assests/men-sneakers-3/men-shoe-5.avif",
    images: [
     "/assests/men-sneakers-3/men-shoe-5.avif",
     "/assests/men-sneakers-3/men-shoe-2.avif",
     "/assests/men-sneakers-3/men-shoe-3.avif",
     "/assests/men-sneakers-3/men-shoe-4.avif",
    ],
    stock: 60,
    rating: "4.8",
    is_in_inventory: true,
    items_left: 60,
    slug: "mainalun-breathable-mid-top-sneakers",
    gender: "Mens",
  },
  {
    id: 4,
    name: "Women'S Solid Color Sports Shoes",
    brand: "Adidas",
    price: 6118,
    category: "Women",
    description:
      "Women'S Solid Color Sports Shoes, Breathable Knitted Low-Top Outdoor Footwear, Comfortable Large Size Shoes for Women., Women Shoes, Sneakers.",
    imageURL: "/assests/snakers-1/women-shoe-1.avif",
    images: [
      "/assests/snakers-1/women-shoe-1.avif",
      "/assests/snakers-1/women-shoe-2.avif",
      "/assests/snakers-1/women-shoe-3.avif",
      "/assests/snakers-1/women-shoe-4.avif",
      "/assests/snakers-1/women-shoe-5.avif",
    ],
    stock: 55,
    rating: "4.7",
    is_in_inventory: true,
    items_left: 55,
    slug: "adidas-women-sneaker",
    gender: "Womens",
  },
  {
    id: 5,
    name: "Leopard Print Sneakers",
    brand: "FILA",
    price: 6709,
    category: "Women",
    description:
      "Women's Breathable Lightweight Sneakers with Leopard Print - Lace-Up Low-Top Casual Shoes Suitable for - Wear, Round Toe & Soft Microfiber Insole - Comfortable Athletic Footwear ZOSIVC (Branding Rights-Owned Product), Women Shoes",

    imageURL: "/assests/sneakers-2/women-shoe-6.avif",
    images: [
      "/assests/sneakers-2/women-shoe-6.avif",
      "/assests/sandals/women-shoe-5.avif",
      "/assests/sneakers-2/women-shoe-1.avif",
      "/assests/sneakers-2/women-shoe-2.avif",
      "/assests/sneakers-2/women-shoe-3.avif",
      "/assests/sneakers-2/women-shoe-4.avif",
    ],
    stock: 55,
    rating: "5.8",
    is_in_inventory: true,
    items_left: 55,
    slug: "FILA-women-sneaker",
    gender: "Womens",
  },
  {
    id: 6,
    name: "Womens-Sandals",
    brand: "Saint Laurent",
    price: 2405,
    category: "Sandals",
    description:
      "Women's Color Block Thick-Soled Sandals, Versatile Open-Toe Classic Summer Shoes, Women Shoes ",
    imageURL: "/assests/sandals/women-shoe-1.avif",
    images: [
      "/assests/sandals/women-shoe-1.avif",
      "/assests/sandals/women-shoe-2.avif",
      "/assests/sandals/women-shoe-3.avif",
      "/assests/sandals/women-shoe-4.avif",
    ],
    stock: 55,
    rating: "4.7",
    is_in_inventory: true,
    items_left: 55,
    slug: "Saint-Laurent-women-sandals",
    gender: "Womens",
  },
];

export default shoesData;
